apiVersion: v1
kind: Pod
metadata:
  labels:
    app: demokube1
  name: demonode
spec:
  containers:
  - name: a1
    image: quylua98/demo-kubernete:0.0.1
    resources:
      limits:
        memory: "150M"
        cpu: "100m"
    ports:
      - containerPort: 8080

    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10